name: flutter_base
description: Flutter Base Application
version: 2.4.24+47
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_smart_retry: ^6.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  google_fonts: ^6.0.0
  hydrated_bloc: ^9.1.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  loggy: ^2.0.3
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  core_dls:
    path: ./packages/core_dls
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.2.3
  carousel_slider: ^5.0.0
  iconly: ^1.0.1
  device_info_plus: ^10.1.0
  flutter_spinkit: ^5.2.0
  package_info_plus: ^8.0.1
  cached_network_image: ^3.4.0
  url_launcher: ^6.3.0
  expansion_tile_card: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0+3
  contained_tab_bar_view: ^0.8.0
  visibility_detector: ^0.4.0+2
  data_table_2: ^2.5.18
  collection: ^1.18.0
  permission_handler: ^11.3.1
  date_picker_plus: ^4.1.0
  table_calendar: ^3.1.2
  file_picker: ^10.2.0
  image_picker: ^1.1.2

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - lib/l10n/arb/
    - .env.development
    - .env.production
    - .env.staging
