name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core_dls:
    path: ../

  equatable: ^2.0.5

  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.7

  # https://pub.dev/packages/reactive_forms
  reactive_forms: ^16.1.0

  # https://pub.dev/packages/reactive_phone_form_field
  reactive_phone_form_field: ^2.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:

  assets:
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
